In [1]:
import torch
import torch.nn.functional as F

In [6]:
x = torch.ones((2, 3, 4))
y = torch.randn((2, 4)).unsqueeze(1) * 2
y-x

tensor([[[ 0.5419,  3.0521, -0.6655, -3.9897],
         [ 0.5419,  3.0521, -0.6655, -3.9897],
         [ 0.5419,  3.0521, -0.6655, -3.9897]],

        [[ 2.7878, -1.9474,  1.9980, -2.3520],
         [ 2.7878, -1.9474,  1.9980, -2.3520],
         [ 2.7878, -1.9474,  1.9980, -2.3520]]])

In [24]:
torch.manual_seed(0)

In [30]:
x = torch.randn(5, 10, 5)
same_index = list(range(5))
x[same_index, :, same_index] = 0
torch.max(x, dim=2)[0]

tensor([[0.8057, 0.0000, 1.4564, 0.4190, 2.5597, 2.4895, 1.4672, 0.0000, 0.8785,
         0.0000],
        [1.1735, 3.0229, 2.0078, 0.8898, 0.6964, 1.0651, 1.8367, 1.3104, 2.2955,
         0.2853],
        [1.8988, 1.5495, 1.9224, 0.0595, 1.2487, 0.8228, 1.0395, 0.9397, 0.0000,
         0.3173],
        [2.2342, 1.4692, 1.8086, 0.1066, 0.9730, 1.6783, 0.6901, 1.0479, 1.6295,
         0.2581],
        [0.3799, 0.9636, 0.4165, 2.7058, 1.5000, 1.3973, 1.0684, 0.0000, 0.6978,
         1.4493]])

In [2]:
x = torch.randn(3, 4, 3)
x

tensor([[[-0.8788,  0.4973, -0.4462],
         [ 0.0513,  0.1919,  1.0148],
         [ 1.3350, -0.7270,  0.2080],
         [ 1.3824,  0.0340, -0.6382]],

        [[-0.9240,  0.9218,  0.4127],
         [-1.0235, -0.1158, -0.3771],
         [-0.6241, -0.6277, -0.5265],
         [-1.5564, -1.1869, -1.8037]],

        [[-1.0898, -0.0616,  0.9723],
         [ 0.4132,  1.8198,  1.8599],
         [-0.5888,  0.5833, -1.8004],
         [-1.0254, -0.5400, -0.7194]]])

In [3]:
-x

tensor([[[ 0.8788, -0.4973,  0.4462],
         [-0.0513, -0.1919, -1.0148],
         [-1.3350,  0.7270, -0.2080],
         [-1.3824, -0.0340,  0.6382]],

        [[ 0.9240, -0.9218, -0.4127],
         [ 1.0235,  0.1158,  0.3771],
         [ 0.6241,  0.6277,  0.5265],
         [ 1.5564,  1.1869,  1.8037]],

        [[ 1.0898,  0.0616, -0.9723],
         [-0.4132, -1.8198, -1.8599],
         [ 0.5888, -0.5833,  1.8004],
         [ 1.0254,  0.5400,  0.7194]]])